alter session set "_oracle_script"=true;

CREATE TABLESPACE JAMBO_MUSIC DATAFILE
  '/opt/oracle/oradata/XE/jambo_music_001.dbf' SIZE 300M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK OFF;

CREATE USER JAMBO_MUSIC IDENTIFIED BY "JAMBO_MUSIC"
       DEFAULT TABLESPACE JAMBO_MUSIC
       TEMPORARY TABLESPACE TEMP
         ACCOUNT UNLOCK;
GRANT CONNECT TO JAMBO_MUSIC;
GRANT RESOURCE TO JAMBO_MUSIC;
GRANT CREATE ANY TYPE TO JAMBO_MUSIC;
ALTER USER JAMBO_MUSIC DEFAULT ROLE ALL;
GRANT UNLIMITED TABLESPACE TO JAMBO_MUSIC;

--TEST
CREATE USER TEST_JAMBO_MUSIC IDENTIFIED BY "TEST_JAMBO_MUSIC"
       DEFAULT TABLESPACE JAMBO_MUSIC
       TEMPORARY TABLESPACE TEMP
         ACCOUNT UNLOCK;
GRANT CONNECT TO TEST_JAMBO_MUSIC;
GRANT RESOURCE TO TEST_JAMBO_MUSIC;
GRANT CREATE ANY TYPE TO TEST_JAMBO_MUSIC;
ALTER USER TEST_JAMBO_MUSIC DEFAULT ROLE ALL;
GRANT UNLIMITED TABLESPACE TO TEST_JAMBO_MUSIC;
